# Note: these settings inherit all settings found in the defaults.yml file.
# See all those base settings here: https://github.com/yarnjs/yarn/blob/master/lib/config/defaults.yml

# Site settings
site:
  title: A Yarn Site
  author: Ya Rn
  email: my@email.com
  description: > # this means to ignore newlines until "baseurl:"
    My yarn site.
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "" # the base hostname & protocol for your site

path:
  source:      ./
  destination: ./_site
  plugins:     ./_plugins
  themes:      ./_themes

# What is the current theme.
theme: 'thread'

plugins:
  html-minifier:
    enabled: false
  excerpt:
    enabled: true
