# Site settings.
# This is where you can put site-wide settings.
# Any values placed here are globally accessible
# from any template context via the `site` key.
site:
  title: My Yarn Title
  email: your-yarn@email.com
  description: > # this means to ignore newlines until "baseurl:"
    Your website's description goes here.
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "http://yourdomain.com" # the base hostname & protocol for your site

# Where things are.
# If you have a unique layout for your site and want to
# change where Yarn looks for certain files you can change
# them here. All files are relative to where the `_config.yml`
# is found.
path:
  source:      ./
  destination: ./_site
  plugins:     ./_plugins
  themes:      ./_themes

# Individual File configuration.
file:
  # What key from a File's frontmatter Yarn should use
  # as the property to grab the URL of the file from.
  url_key: url

# This is where you configure your collections of content.
# For more details refer to the Collections documentation.
collections:
  default:
    path: ./
    template: page
  favicon:
    path: favicon.ico
    static: true
  images:
    path: ./images
    static: true
  post:
    path: ./_posts
    template: post
    permalink: /:title/
    filter:
      metadata:
        draft: true
      future_date:
        key: date
    sort:
      key: date
      order: descending
    pagination:
      template: index
      size: 6
      permalink_index: /
      permalink_page:  /page/:page/
  tag:
    metadata: tags
    sort:
      key: date
      order: descending
    filter:
      metadata:
        draft: true
      future_date:
        key: date
    pagination:
      template: tag
      size: 6
      permalink_index: /tag/:metadata/
      permalink_page:  /tag/:metadata/:page/

# Current theme.
# What theme your Yarn site should use when building your site.
theme: 'thread'

# If we should remove the compile destination folder before writing.
clean_destination: false

# What file extensions we should recognize as a markdown file.
markdown_extension:
  - markdown
  - mkdown
  - mkdn
  - mkd
  - md

# Slug options.
# Options passed to node-slug
slug:
  lower: true

# Conversion.
# What markdown conversion tool we should use.
markdown:    remarkable
highlighter: highlight.js

# Markdown Processor.
# This lets you customize the markdown processor defined above.
remarkable:
  preset:       'commonmark'
  highlight:    true

# Serving.
# When running `yarn serve` what settings should be used.
server:
  port:    8080
  host:    127.0.0.1
  baseurl: "" # does not include hostname

quiet:    false

# Where files created via `yarn new` should be placed.
new_file_permalink: '/_posts/:date|YYYY-:date|MM-:date|D-:title.md'

# What plugins you want enabled and what configuration settings they should have.
plugins:
  html-minifier:
    enabled: false
    options:
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeAttributeQuotes: true
  excerpt:
    enabled: true